name: Build Flutter Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up Java 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # Step 2: Get our app's source code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 3: Set up the Flutter SDK
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    # Step 4: Manually create the Android build files
    - name: Create required Android build files
      run: |
        # Create all necessary parent directories first
        mkdir -p android/app/src/main 
        # Now create the files inside those directories
        echo 'android { ndkVersion = "27.0.12077973" }' > android/app/build.gradle.kts
        echo '<manifest xmlns:android="http://schemas.android.com/apk/res/android"><application android:name="${applicationName}" android:label="fidel_listen_app" android:icon="@mipmap/ic_launcher"><activity android:name=".MainActivity" android:exported="true" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize"><meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" /><intent-filter><action android:name="android.intent.action.MAIN"/><category android:name="android.intent.category.LAUNCHER"/></intent-filter></activity><meta-data android:name="flutterEmbedding" android:value="2" /></application></manifest>' > android/app/src/main/AndroidManifest.xml

    # Step 5: Get all the app's dependencies
    - name: Get Flutter dependencies
      run: flutter pub get

    # Step 6: Run the build_runner
    - name: Run build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs

    # Step 7: Build the actual .apk file
    - name: Build APK
      run: flutter build apk --release
      
    # Step 8: Upload the finished .apk file
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: fidel-listen-app-apk
        path: build/app/outputs/flutter-apk/app-release.apk
