name: Build Flutter Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up the CORRECT Java environment (Java 17)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # Step 2: Checkout the OFFICIAL Flutter starter project. This is guaranteed to be valid.
    - name: Checkout a valid Flutter project
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.19.0' # Using a specific stable version
        
    - run: flutter create --template=app .

    # Step 3: Get OUR app's source code from our repository
    - name: Checkout our app source
      uses: actions/checkout@v4
      with:
        path: 'our_app' # Put our code into a temporary folder

    # Step 4: Prepare the project structure
    - name: Prepare project
      run: |
        # Delete the sample lib directory from the valid project
        rm -rf lib
        # Copy our pubspec.yaml file, overwriting the default one
        cp our_app/app_source/pubspec.yaml .
        # Copy our entire lib folder
        cp -r our_app/app_source/lib .
        # Copy our entire assets folder
        cp -r our_app/assets .

    # Step 5: Get all the app's dependencies based on our pubspec
    - name: Get Flutter dependencies
      run: flutter pub get

    # Step 6: Run the build_runner
    - name: Run build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs
    
    # Step 7: THIS IS THE NDK FIX. We create the file that Gradle needs.
    - name: Create required Android build file
      run: |
        mkdir -p android/app
        echo 'android { ndkVersion = "27.0.12077973" }' > android/app/build.gradle.kts

    # Step 8: Build the actual .apk file
    - name: Build APK
      run: flutter build apk --release
      
    # Step 9: Upload the finished .apk file
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: fidel-listen-app-apk
        path: build/app/outputs/flutter-apk/app-release.apk
