name: Build Flutter Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up the Java environment
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    # Step 2: Set up the Flutter SDK
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    # Step 3: THE NEW FIX! Create a blank, valid project first.
    - name: Create a new Flutter project
      run: flutter create --project-name fidel_listen_final .

    # Step 4: Get your code from the repository and place it into the project
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 5: Get all the app's dependencies
    - name: Get Flutter dependencies
      run: flutter pub get
      
# Step 5.5: Automatically create missing Android/iOS files
    - name: Create platform-specific files
      run: flutter create .
      
    # Step 6: Run the build_runner
    - name: Run build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs

    # Step 7: Build the actual .apk file
    - name: Build APK
      run: flutter build apk --release

    # Step 8: Upload the finished .apk file
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: fidel-listen-app-apk
        path: build/app/outputs/flutter-apk/app-release.apk
