name: Build Flutter Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up the CORRECT Java environment (Java 17)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # Step 2: Set up the Flutter SDK
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    # Step 3: Get our source code from the repository
    - name: Checkout source code
      uses: actions/checkout@v4

    # Step 4: THE NEW, SIMPLIFIED FIX
    # We will now create a valid project and move our code into it, all in one place.
    - name: Prepare Project For Build
      run: |
        # Create a temporary folder for our source
        mkdir temp_source
        # Move our app's source code into the temporary folder
        mv app_source/* temp_source/
        # Create a fresh, valid project in the current directory
        flutter create --project-name fidel_listen_final .
        # Copy our source code from the temp folder into the fresh project
        cp -r temp_source/* .

    # Step 5: Get all the app's dependencies
    - name: Get Flutter dependencies
      run: flutter pub get

    # Step 6: Run the build_runner
    - name: Run build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs

    # Step 7: Build the actual .apk file
    - name: Build APK
      run: flutter build apk --release
      
    # Step 8: Upload the finished .apk file. The path is now simple.
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: fidel-listen-app-apk
        path: build/app/outputs/flutter-apk/app-release.apk
