name: Build Flutter Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up Java 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # Step 2: Set up a valid Flutter project foundation
    - name: Checkout a valid Flutter project
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.19.0'
    - run: flutter create --template=app .

    # Step 3: Get OUR app's source code
    - name: Checkout our app source
      uses: actions/checkout@v4
      with:
        path: 'our_app'

    # Step 4: Prepare the project structure
    - name: Prepare project
      run: |
        rm -rf lib
        cp our_app/app_source/pubspec.yaml .
        cp -r our_app/app_source/lib .
        cp -r our_app/assets .

    # Step 5: Get all the app's dependencies
    - name: Get Flutter dependencies
      run: flutter pub get

    # Step 6: Run the build_runner
    - name: Run build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs
    
    # Step 7: Create the required NDK version file
    - name: Create required Android build file
      run: |
        mkdir -p android/app
        echo 'android { ndkVersion = "27.0.12077973" }' > android/app/build.gradle.kts

    # --- THIS IS THE DEBUGGING STEP ---
    # Step 7.5: List all files right before the build
    - name: List final file structure
      run: ls -R

    # Step 8: Build the APK
    - name: Build APK
      run: flutter build apk --release
      
    # Step 9: Upload the finished .apk file
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: fidel-listen-app-apk
        path: build/app/outputs/flutter-apk/app-release.apk
