name: Build Flutter Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up Java 17 (This fixes the Gradle plugin error)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # Step 2: Get our app's source code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 3: Set up the Flutter SDK
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    # Step 4: Create the NDK version file BEFORE the build
    # This fixes the camera/tts plugin error
    - name: Create required Android build file
      run: |
        # Create the folders if they don't exist
        mkdir -p android/app
        # Create the file with the correct NDK version
        echo 'android { ndkVersion = "27.0.12077973" }' > android/app/build.gradle.kts
    
    # Step 5: Get all the app's dependencies
    - name: Get Flutter dependencies
      run: flutter pub get

    # Step 6: Run the build_runner
    - name: Run build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs

    # Step 7: Build the actual .apk file
    - name: Build APK
      run: flutter build apk --release
      
    # Step 8: Upload the finished .apk file
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: fidel-listen-app-apk
        path: build/app/outputs/flutter-apk/app-release.apk
