name: Build Flutter Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Get your code from the repository (Updated to v4)
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up the Java environment, which Flutter needs for Android
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    # Step 3: Set up the Flutter SDK on the virtual machine
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    # Step 4: Get all the app's dependencies
    - name: Get Flutter dependencies
      run: flutter pub get

    # Step 5: Run the build_runner to generate necessary files
    - name: Run build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs
    # Step 5.5: Automatically create missing Android/iOS files
    - name: Create platform-specific files
      run: flutter create .
    # Step 6: Build the actual .apk file
    - name: Build APK
      run: flutter build apk --release

    # Step 7: Upload the finished .apk file (Updated to v4)
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: fidel-listen-app-apk
        path: build/app/outputs/flutter-apk/app-release.apk
